import { Component } from '@angular/core';
import { Movie } from '../movie';

@Component({
  selector: 'app-movies',
  templateUrl: './movies.component.html',
  styleUrls: ['./movies.component.scss'],
})
export class MoviesComponent {
  movies: Movie[] = [
    {
      Title: 'Batman Begins',
      Year: '2005',
      Rated: 'PG-13',
      Released: '15 Jun 2005',
      Runtime: '140 min',
      Genre: 'Action, Crime, Drama',
      Director: 'Christopher Nolan',
      Writer: 'Bob Kane, David S. Goyer, Christopher Nolan',
      Actors: 'Christian Bale, Michael Caine, Ken Watanabe',
      Plot: 'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.',
      Language: 'English, Mandarin',
      Country: 'United States, United Kingdom',
      Awards: 'Nominated for 1 Oscar. 14 wins & 79 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '8.2/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '84%',
        },
        {
          Source: 'Metacritic',
          Value: '70/100',
        },
      ],
      Metascore: '70',
      imdbRating: '8.2',
      imdbVotes: '1,483,454',
      imdbID: 'tt0372784',
      Type: 'movie',
      DVD: '18 Oct 2005',
      BoxOffice: '$206,863,479',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Batman v Superman: Dawn of Justice',
      Year: '2016',
      Rated: 'PG-13',
      Released: '25 Mar 2016',
      Runtime: '151 min',
      Genre: 'Action, Adventure, Sci-Fi',
      Director: 'Zack Snyder',
      Writer: 'Chris Terrio, David S. Goyer, Bob Kane',
      Actors: 'Ben Affleck, Henry Cavill, Amy Adams',
      Plot: 'Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.',
      Language: 'English',
      Country: 'United States',
      Awards: '14 wins & 31 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '6.4/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '29%',
        },
        {
          Source: 'Metacritic',
          Value: '44/100',
        },
      ],
      Metascore: '44',
      imdbRating: '6.4',
      imdbVotes: '706,281',
      imdbID: 'tt2975590',
      Type: 'movie',
      DVD: '19 Jul 2016',
      BoxOffice: '$330,360,194',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'The Batman',
      Year: '2022',
      Rated: 'PG-13',
      Released: '04 Mar 2022',
      Runtime: '176 min',
      Genre: 'Action, Crime, Drama',
      Director: 'Matt Reeves',
      Writer: 'Matt Reeves, Peter Craig, Bob Kane',
      Actors: 'Robert Pattinson, Zoë Kravitz, Jeffrey Wright',
      Plot: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
      Language: 'English, Spanish, Latin, Italian',
      Country: 'United States',
      Awards: 'Nominated for 3 Oscars. 23 wins & 150 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '7.8/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '85%',
        },
        {
          Source: 'Metacritic',
          Value: '72/100',
        },
      ],
      Metascore: '72',
      imdbRating: '7.8',
      imdbVotes: '674,068',
      imdbID: 'tt1877830',
      Type: 'movie',
      DVD: '19 Apr 2022',
      BoxOffice: '$369,345,583',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Batman',
      Year: '1989',
      Rated: 'PG-13',
      Released: '23 Jun 1989',
      Runtime: '126 min',
      Genre: 'Action, Adventure',
      Director: 'Tim Burton',
      Writer: 'Bob Kane, Sam Hamm, Warren Skaaren',
      Actors: 'Michael Keaton, Jack Nicholson, Kim Basinger',
      Plot: 'The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.',
      Language: 'English, French, Spanish',
      Country: 'United States, United Kingdom',
      Awards: 'Won 1 Oscar. 10 wins & 26 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BZDNjOGNhN2UtNmNhMC00YjU4LWEzMmUtNzRkM2RjN2RiMjc5XkEyXkFqcGdeQXVyMTU0OTM5ODc1._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '7.5/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '73%',
        },
        {
          Source: 'Metacritic',
          Value: '69/100',
        },
      ],
      Metascore: '69',
      imdbRating: '7.5',
      imdbVotes: '383,053',
      imdbID: 'tt0096895',
      Type: 'movie',
      DVD: '22 Aug 1997',
      BoxOffice: '$251,409,241',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Batman Returns',
      Year: '1992',
      Rated: 'PG-13',
      Released: '19 Jun 1992',
      Runtime: '126 min',
      Genre: 'Action, Crime, Fantasy',
      Director: 'Tim Burton',
      Writer: 'Bob Kane, Daniel Waters, Sam Hamm',
      Actors: 'Michael Keaton, Danny DeVito, Michelle Pfeiffer',
      Plot: 'While Batman deals with a deformed man calling himself the Penguin wreaking havoc across Gotham with the help of a cruel businessman, a female employee of the latter becomes the Catwoman with her own vendetta.',
      Language: 'English',
      Country: 'United States, United Kingdom',
      Awards: 'Nominated for 2 Oscars. 2 wins & 29 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '7.1/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '81%',
        },
        {
          Source: 'Metacritic',
          Value: '68/100',
        },
      ],
      Metascore: '68',
      imdbRating: '7.1',
      imdbVotes: '310,598',
      imdbID: 'tt0103776',
      Type: 'movie',
      DVD: '22 Aug 1997',
      BoxOffice: '$162,924,631',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Batman & Robin',
      Year: '1997',
      Rated: 'PG-13',
      Released: '20 Jun 1997',
      Runtime: '125 min',
      Genre: 'Action, Sci-Fi',
      Director: 'Joel Schumacher',
      Writer: 'Bob Kane, Akiva Goldsman',
      Actors: "Arnold Schwarzenegger, George Clooney, Chris O'Donnell",
      Plot: 'Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City.',
      Language: 'English',
      Country: 'United States, United Kingdom',
      Awards: '10 wins & 22 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg',
      Ratings: [
        {
          Source: 'Internet Movie Database',
          Value: '3.7/10',
        },
        {
          Source: 'Rotten Tomatoes',
          Value: '12%',
        },
        {
          Source: 'Metacritic',
          Value: '28/100',
        },
      ],
      Metascore: '28',
      imdbRating: '3.7',
      imdbVotes: '257,380',
      imdbID: 'tt0118688',
      Type: 'movie',
      DVD: '21 Oct 1997',
      BoxOffice: '$107,353,792',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
  ];
}
